apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.hello.world
spec:
  group: hello.world
  names:
    kind: HelloWorld
    listKind: HelloWorldList
    plural: helloworlds
    singular: helloworld
  scope: Namespaced
  version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-operator
  template:
    metadata:
      labels:
        name: k8s-operator
    spec:
      containers:
        - name: k8s-operator
          image: batazor/k8s-operator:v1.0.0
          command:
          - k8s-operator
          imagePullPolicy: Always
